### ISSUE TITLE
Question about Spatial-CUT&Tag data analysis

### ISSUE THREAD

**Issue by feiyoung** [dyxmvp/spatial-CUT-Tag#1]
Recently, I read your new outstanding work ‘Spatial-CUT&Tag: Spatially resolved chromatin modification profiling at the cellular level’ on Science. I am very interested in this promising technology, so I try analyzing the mouse olfactory bulb data (GSM5028441_OB_H3K27me3_20um.fragments.tsv.gz) and mouse embryo E11 data (GSM5028434_ME11_H3K27me3_50um.fragments.tsv.gz) used in the paper according to the code in the Github repository (https://github.com/dyxmvp/spatial-CUT-Tag/blob/main/Data_visualization/archR.R.
When running the code, I only changed the input file name (inputFiles object in the code) and sample name (sampleNames object in the code), but I cannot obtain the similar clustering results to that in the paper.  I do not know what is wrong, so I would like to ask how can I reproduce the similar results? Thank you very much!

**Comment by dyxmvp** [comment]
Hi, Can you upload the code you are using? I analyzed the data on my end and got the same results in the paper.

**Comment by feiyoung** [comment]
Thank you for your reply. I have solved this problem. I did not match the IDs (barcodes) of clusters and spatial coordinates, so the spatial heatmap is messy.  The archR.R script is of no problem. Thank you again!
